# Mongo settings.
mongo:
  host: localhost
  port: 27017
  database: test

# Database settings.
database:

  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: postgres

  # the password
  password: postgres

  # the JDBC URL
  url: jdbc:postgresql://localhost:5432/example
  
  autoCommitByDefault: false
  
  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.github.master_of_sugar: DEBUG

  appenders:
    - type: console